version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - DB_INIT=true
      - MONGO_URI=mongodb://mongo:27017/sketch_db
    depends_on:
      - mongo


  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:

